ItlaTwitter/Controllers/AmigosController.cs
using AutoMapper;
using ItlaTwitter.Models;
using ItlaTwitter.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ItlaTwitter.Controllers
{
    public class AmigosController : Controller
    {


        private readonly itlaTwitterContext _context;
        private readonly IMapper _mapper;


        public AmigosController(itlaTwitterContext context, IMapper mapper)
        {
            _context = context;
            this._mapper = mapper;

        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userTokens = HttpContext.Session.GetInt32("TokenUser");
            if (string.IsNullOrEmpty(userTokens.ToString()))
            {
                return RedirectToAction("Redirect", "Login");
            }
            var amigos = await _context.Amigos.Where(m => m.Idenvia == userTokens).ToListAsync();
            var listOfListCom = new List<List<ComentariosViewModel>>();
            var Listdatoamigos = new List<Usuarios>();

            foreach (Amigos idp in amigos)
            {
                var datoamigos =  _context.Usuarios.FirstOrDefault(m => m.Id == idp.Idrecibe);
              var publicacionesdeltipo  = await _context.Publicaciones.Where(m => m.Idusuario == idp.Idrecibe).OrderByDescending(a => a.Fecha).ToListAsync();
                foreach (Publicaciones pub in publicacionesdeltipo)
                {
                    var comentarios = _context.Comentario.Where(b => (b.Idpublicacion == pub.Id)).ToList();
                    List<ComentariosViewModel> cometariosview = new List<ComentariosViewModel>();

                    foreach (var Comento in comentarios)
                    {

                        var sabercomentarista = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == Comento.Idusuario);
                        var cvms = _mapper.Map<ComentariosViewModel>(Comento);
                        cvms.Comentarista = sabercomentarista.Usuario;

                        cometariosview.Add(cvms);

                    }
                    listOfListCom.Add(cometariosview);

                  
                }

                Listdatoamigos.Add(datoamigos);

            }
            
           var pubs = _context.Publicaciones2.FromSqlRaw("SELECT I.id,I.contenido,I.idusuario, Nombre, Apellido, Usuario,Fecha FROM Usuarios O JOIN Publicaciones I ON O.id = I.idusuario JOIN Amigos P ON P.idrecibe = I.idusuario where P.idenvia ={0} ORDER BY i.Fecha desc", userTokens).ToList() ;
            
            AmigosViewModel vms = new AmigosViewModel();
            vms.idusuario = userTokens.GetValueOrDefault() ;
            vms.Amigos = Listdatoamigos;
            vms.publicacion = pubs;
            vms.comentario = listOfListCom;

            return View(vms);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(AmigosViewModel vms, string submit, string coment)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var userTokens = HttpContext.Session.GetInt32("TokenUser");
            vms.idusuario = userTokens.GetValueOrDefault();
            switch (submit)
            {
                case "AñadirA":
                    var añadir= await _context.Usuarios.FirstOrDefaultAsync(a => a.Usuario == vms.Añadiruser.Trim());

                    var añadiramigo = new Amigos();
                    añadiramigo.Idenvia = vms.idusuario;
                    añadiramigo.Idrecibe = añadir.Id;

                    await _context.Amigos.AddAsync(añadiramigo);
                    await _context.SaveChangesAsync();

                    break;
                case "BorrarAmix":
                    var Borrar = await _context.Amigos.FirstOrDefaultAsync(a => a.Idenvia == vms.idusuario && a.Idrecibe == vms.BorrarAmix);

                    if (Borrar != null)
                    {
                        _context.Amigos.Remove(Borrar);
                        await _context.SaveChangesAsync();
                    }


                    break;
                case "Comentar":
                    if (coment != null)
                    {
                        vms.nuevoCom.Contenido = coment;
                        vms.nuevoCom.Idusuario = userTokens;
                        _context.Comentario.Add(vms.nuevoCom);
                        await _context.SaveChangesAsync();
                    }
                    break;
             
                default:
                    throw new Exception();

            }

            var amigos = await _context.Amigos.Where(m => m.Idenvia == userTokens).ToListAsync();
            var listOfListCom = new List<List<ComentariosViewModel>>();
            var Listdatoamigos = new List<Usuarios>();

            foreach (Amigos idp in amigos)
            {
                var datoamigos = _context.Usuarios.FirstOrDefault(m => m.Id == idp.Idrecibe);
                var publicacionesdeltipo = await _context.Publicaciones.Where(m => m.Idusuario == idp.Idrecibe).OrderByDescending(a => a.Fecha).ToListAsync();
                foreach (Publicaciones pub in publicacionesdeltipo)
                {
                    var comentarios = _context.Comentario.Where(b => (b.Idpublicacion == pub.Id)).ToList();
                    List<ComentariosViewModel> cometariosview = new List<ComentariosViewModel>();

                    foreach (var Comento in comentarios)
                    {

                        var sabercomentarista = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == Comento.Idusuario);
                        var cvms = _mapper.Map<ComentariosViewModel>(Comento);
                        cvms.Comentarista = sabercomentarista.Usuario;

                        cometariosview.Add(cvms);

                    }
                    listOfListCom.Add(cometariosview);

              

                }

                Listdatoamigos.Add(datoamigos);

            }

            var pubs = _context.Publicaciones2.FromSqlRaw("SELECT I.id,I.contenido,I.idusuario, Nombre, Apellido, Usuario,Fecha FROM Usuarios O JOIN Publicaciones I ON O.id = I.idusuario JOIN Amigos P ON P.idrecibe = I.idusuario where P.idenvia ={0} ORDER BY i.Fecha desc", userTokens).ToList();

            vms.Amigos = Listdatoamigos;
            vms.publicacion = pubs;
            vms.comentario = listOfListCom;

            return View(vms);

        }
        [AcceptVerbs("GET", "POST")]
        public IActionResult ReturnUser(string Añadiruser)
        {
           var userTokens = HttpContext.Session.GetInt32("TokenUser");

            var user = _context.Usuarios.FirstOrDefault(c =>
               c.Usuario == Añadiruser);
           
            if (user != null)
            {
                var revisaramigo = _context.Amigos.FirstOrDefault(a => a.Idenvia == userTokens && a.Idrecibe == user.Id);


                 if (revisaramigo != null)
                {

                    return Json($"Ya tienes añadido este Usuario {Añadiruser}");

                }
                else if (user.Id == userTokens)
                {
                    return Json($"No puedes añadirte a ti mismo");

                }
                else {

                    return Json(true);


                }

            }
            
            return Json($"Este Usuario {Añadiruser} no existe");
        }


    }
}
   

ItlaTwitter/Controllers/LoginController.cs
using AutoMapper;
using EmailHandler;
using ItlaTwitter.Models;
using ItlaTwitter.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;


namespace ItlaTwitter.Controllers
{
    public class LoginController : Controller
    {

        private readonly itlaTwitterContext _context;
        private readonly Iemailsender _iemailsender;
        private readonly IMapper _mapper;

        public LoginController(itlaTwitterContext context, Iemailsender iemailsender, IMapper mapper)
        {
            _context = context;
            _iemailsender = iemailsender;
            this._mapper = mapper;
        }

        public IActionResult Index()
        {
            var userTokens = HttpContext.Session.GetInt32("TokenUser");
            if (userTokens != null)
            {
                return RedirectToAction("Index", "Usuarios");
            }


          ViewBag.mostrar = "none";


            return View();
        }
        [HttpPost]
        public async Task <IActionResult> Index(LoginViewModel vm)
        {

            ViewBag.mostrar = "none";

            if (ModelState.IsValid)
            {
                var user = await _context.Usuarios.FirstOrDefaultAsync(c =>
                c.Usuario== vm.usuario  && c.Contraseña == PasswordEncryption(vm.Contraseña));
                
                if (user != null)
                {
                    if (user.Estado.Trim() == "Activo")
                    {
                        HttpContext.Session.SetInt32("TokenUser", user.Id);
                        return RedirectToAction("Index", "Usuarios");

                    }
                   if (user.Estado.Trim() == "Inactivo")
                    {
                        ViewBag.mostrar = "block";

                    }

                } else
                {
                    ModelState.AddModelError("UsuarioOcontraseñaerronaea", "El usuario ingresado o contraseña estan erroneos");
                }
               
            }


            return View(vm);
        }


        [HttpGet]

        public IActionResult Registrar()
        {
            var userTokens = HttpContext.Session.GetInt32("TokenUser");
            if (userTokens != null)
            {
                return RedirectToAction("Index", "Usuarios");
            }
            ViewBag.mostrar = "none";

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(RegisterViewModel vm)
        {
            ViewBag.mostrar = "none";

            if (!ModelState.IsValid)
            {
                return View();
            }
            vm.Telefono = string.Format("{0}-{1}", vm.indicetel, vm.Telefono).Trim();
            vm.Contraseña = PasswordEncryption(vm.Contraseña).Trim();
            var usuarioentity = _mapper.Map<Usuarios>(vm);

            string url = Request.GetDisplayUrl().Replace("Registrar", "Activador");

            _context.Usuarios.Add(usuarioentity);
            await _context.SaveChangesAsync();
            var message = new Message(new string[] { vm.Correo }, "Activacion de Cuenta", "¡Bienvenido a Itla Twitter!, \n " + usuarioentity.Nombre + " " + usuarioentity.Apellido + " \n Gracias por ingresar a la familia ITLA, esperamos que disfrutes de esta aplicacion y puedas sacarle todo el potencial que tiene escondio \n Este es el link para activar la cuenta del Usuario " +  usuarioentity.Usuario+":"+ " \n" +url+"/"+ usuarioentity.Id);
            await _iemailsender.SendMailAsync(message);
            ViewBag.mostrar = "block";
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Activador(int? id)
        {
            var userTokens = HttpContext.Session.GetInt32("TokenUser");
            if (userTokens != null)
            {
                return RedirectToAction("Index", "Usuarios");
            }
            if (id == null)
            {
                return NotFound();
            }

            var Usuario = await _context.Usuarios.FirstOrDefaultAsync(m => m.Id == id);

            if (Usuario == null)
            {
                return NotFound();
            }
            Usuario.Estado = "Activo".Trim();
            _context.Usuarios.Update(Usuario);
              await _context.SaveChangesAsync();
            
            


            return  View();
        }
        [HttpGet]
        public IActionResult Recuperar()
        {
            var userTokens = HttpContext.Session.GetInt32("TokenUser");
            if (userTokens != null)
            {
                return RedirectToAction("Index", "Usuarios");
            }
            ViewBag.mostrar = "none";

            return View();
        }
        [HttpPost]
        public async Task <IActionResult> Recuperar(RecuperarViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var user = _context.Usuarios.FirstOrDefault(c =>
              c.Usuario == vm.usuario);
            Random rnd = new Random();
            int nuevacontraseña = rnd.Next(100000, 999999);

            user.Contraseña = PasswordEncryption(Convert.ToString( nuevacontraseña));
            _context.Usuarios.Update(user);
            await _context.SaveChangesAsync();
            var message = new Message(new string[] {user.Correo}, "Recuperacion de Cuenta", "Hemos sidos notificados que que has perdido tu contraseña para acceder a ITLA Twiiter \nEsta es tu nueva Contraseña " + user.Usuario.Trim()+ ":\n" + nuevacontraseña); ;
            await _iemailsender.SendMailAsync(message);
            
            return View();
        }
        public IActionResult Salir()
        {

            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
        public IActionResult Redirect()
        {
            
            return View();
        }

        [AcceptVerbs("GET", "POST")]
        public  IActionResult VerifyUser(string usuario)
        {
            var user =  _context.Usuarios.FirstOrDefault(c =>
                c.Usuario == usuario );
            if (user != null)
            {
                return Json($"El Usuaurio {usuario} ya esta en uso.");
            }

            return Json(true);
        }
        [AcceptVerbs("GET", "POST")]
        public IActionResult ReturnUser(string usuario)
        {
            var user = _context.Usuarios.FirstOrDefault(c =>
               c.Usuario == usuario);
            if (user != null)
            {
                return Json(true);

            }

            return Json($"Este Usuario {usuario} no existe");
        }
        private string PasswordEncryption (string password)
        {
            using (SHA256 sha256hash = SHA256.Create())
            {

                byte[] bytes = sha256hash.ComputeHash(Encoding.UTF8.GetBytes(password));
                StringBuilder builder = new StringBuilder();
                foreach (Byte t in bytes)
                {

                    builder.Append(t.ToString("x2"));
                }
                return builder.ToString();
            }

        }


    }

}

ItlaTwitter/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ItlaTwitter</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://use.fontawesome.com/8f3f7213dc.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Usuarios" asp-action="Index">
                    <img src="~/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    Itla Twitter
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Amigos" asp-action="Index">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                Amigos
                            </a>
                        </li>
                        <li class="nav-item ml-auto mr-1">
                            <a class="nav-link text-dark " asp-controller="Login" asp-action="Salir">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                Cerrar Sesion
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ItlaTwitter
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ItlaTwitter/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ItlaTwitter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>